/* Generated By:JavaCC: Do not edit this line. ExprConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExprConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TOKEN_ENTIER = 3;
  /** RegularExpression Id. */
  int TOKEN_LET = 4;
  /** RegularExpression Id. */
  int TOKEN_IDENTIF = 5;
  /** RegularExpression Id. */
  int TOKEN_EOL = 6;
  /** RegularExpression Id. */
  int TOKEN_PAR_OUV = 7;
  /** RegularExpression Id. */
  int TOKEN_PAR_FER = 8;
  /** RegularExpression Id. */
  int TOKEN_PLUS = 9;
  /** RegularExpression Id. */
  int TOKEN_MOINS = 10;
  /** RegularExpression Id. */
  int TOKEN_MULT = 11;
  /** RegularExpression Id. */
  int TOKEN_DIV = 12;
  /** RegularExpression Id. */
  int TOKEN_CRO_OUV = 13;
  /** RegularExpression Id. */
  int TOKEN_CRO_FER = 14;
  /** RegularExpression Id. */
  int TOKEN_PT_VIRGULE = 15;
  /** RegularExpression Id. */
  int TOKEN_2_PTS = 16;
  /** RegularExpression Id. */
  int TOKEN_CAR = 17;
  /** RegularExpression Id. */
  int TOKEN_ACC_OUV = 18;
  /** RegularExpression Id. */
  int TOKEN_ACC_FER = 19;
  /** RegularExpression Id. */
  int TOKEN_VIRGULE = 20;
  /** RegularExpression Id. */
  int TOKEN_EQUAL = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<TOKEN_ENTIER>",
    "\"let\"",
    "<TOKEN_IDENTIF>",
    "<TOKEN_EOL>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\"[A-Za-z]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"=\"",
  };

}
